//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace z_quiz.api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Choices()
        {
            this.QuizItems = new HashSet<QuizItems>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int Score { get; set; }
    
        public virtual Questions Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuizItems> QuizItems { get; set; }
    }
}
