//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace z_quiz.api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZQuizModelContainer : DbContext
    {
        public ZQuizModelContainer()
            : base("name=ZQuizModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Testers> Testers { get; set; }
        public virtual DbSet<Questions> Questions { get; set; }
        public virtual DbSet<Choices> Choices { get; set; }
        public virtual DbSet<QuizItems> QuizItems { get; set; }
    }
}
